In [2]:
import pandas as pd
import numpy as np
import atoti as tt
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('clean/worldbank_clean.csv')

print(f"Shape data: {df.shape}")
print(f"Kolom: {list(df.columns)}")
print(f"Tahun: {sorted(df['year'].unique())}")
print(f"Negara: {sorted(df['economy'].unique())}")
df.head(10)

Welcome to Atoti 0.9.15!

By using this community edition, you agree with the license available at https://docs.activeviam.com/products/atoti/python-sdk/latest/eula.html.
Browse the official documentation at https://docs.activeviam.com/products/atoti/python-sdk.
Join the community at https://www.atoti.io/register.

Atoti collects telemetry data, which is used to help understand how to improve the product.
If you don't wish to send usage data, you can request a trial license at https://www.atoti.io/evaluation-license-request.

You can hide this message by setting the `ATOTI_HIDE_EULA_MESSAGE` environment variable to True.
Shape data: (30, 8)
Kolom: ['economy', 'year', 'inflation_pct', 'gdp_usd', 'unemployment_pct', 'population', 'quarter', 'period']
Tahun: [np.int64(2022), np.int64(2023), np.int64(2024)]
Negara: ['BRN', 'IDN', 'KHM', 'LAO', 'MMR', 'MYS', 'PHL', 'SGP', 'THA', 'VNM']

,economy,year,inflation_pct,gdp_usd,unemployment_pct,population,quarter,period
0,BRN,2022,3.682250,1.668154e+10,5.191,455370.0,Q1,2022-Q1
1,BRN,2023,0.357064,1.509508e+10,5.296,458949.0,Q1,2023-Q1
2,BRN,2024,-0.388674,1.534081e+10,5.180,462721.0,Q1,2024-Q1
3,IDN,2022,4.209465,1.319101e+12,3.462,278830529.0,Q1,2022-Q1
4,IDN,2023,3.669387,1.371169e+12,3.308,281190067.0,Q1,2023-Q1
5,IDN,2024,2.181513,1.396300e+12,3.301,283487931.0,Q1,2024-Q1
6,KHM,2022,5.343703,3.999453e+10,0.245,17201724.0,Q1,2022-Q1
7,KHM,2023,2.127468,4.233565e+10,0.256,17423880.0,Q1,2023-Q1
8,KHM,2024,0.808042,4.635265e+10,0.254,17638801.0,Q1,2024-Q1
9,LAO,2022,22.956223,1.546879e+10,1.209,7559007.0,Q1,2022-Q1

In [3]:
country_map = {
    'IDN': 'Indonesia', 'MYS': 'Malaysia', 'THA': 'Thailand',
    'SGP': 'Singapore', 'PHL': 'Philippines', 'VNM': 'Vietnam',
    'MMR': 'Myanmar', 'KHM': 'Cambodia', 'LAO': 'Laos', 'BRN': 'Brunei'
}

df['country_name']  = df['economy'].map(country_map)
df['region']        = 'ASEAN'
df['year']          = df['year'].astype(int)
df['gdp_usd']           = pd.to_numeric(df['gdp_usd'], errors='coerce')
df['inflation_pct']     = pd.to_numeric(df['inflation_pct'], errors='coerce')
df['unemployment_pct']  = pd.to_numeric(df['unemployment_pct'], errors='coerce')
df['population']        = pd.to_numeric(df['population'], errors='coerce')
df['gdp_billion_usd']   = df['gdp_usd'] / 1e9

print(df.dtypes)
print(f"\nMissing values:\n{df.isnull().sum()}")
df.head()

economy              object
year                  int64
inflation_pct       float64
gdp_usd             float64
unemployment_pct    float64
population          float64
quarter              object
period               object
country_name         object
region               object
gdp_billion_usd     float64
dtype: object

Missing values:
economy             0
year                0
inflation_pct       0
gdp_usd             0
unemployment_pct    0
population          0
quarter             0
period              0
country_name        0
region              0
gdp_billion_usd     0
dtype: int64

,economy,year,inflation_pct,gdp_usd,unemployment_pct,population,quarter,period,country_name,region,gdp_billion_usd
0,BRN,2022,3.682250,1.668154e+10,5.191,455370.0,Q1,2022-Q1,Brunei,ASEAN,16.681536
1,BRN,2023,0.357064,1.509508e+10,5.296,458949.0,Q1,2023-Q1,Brunei,ASEAN,15.095085
2,BRN,2024,-0.388674,1.534081e+10,5.180,462721.0,Q1,2024-Q1,Brunei,ASEAN,15.340809
3,IDN,2022,4.209465,1.319101e+12,3.462,278830529.0,Q1,2022-Q1,Indonesia,ASEAN,1319.101183
4,IDN,2023,3.669387,1.371169e+12,3.308,281190067.0,Q1,2023-Q1,Indonesia,ASEAN,1371.169302

Buat Session & Load data

In [9]:
session = tt.Session.start()
table = session.read_pandas(df, table_name="EconomyASEAN")
print("Session & table berhasil dibuat ✓")
table.head()

Session & table berhasil dibuat ✓

,economy,year,inflation_pct,gdp_usd,unemployment_pct,population,quarter,period,country_name,region,gdp_billion_usd
0,BRN,2022,3.68225,16681536466.7183,5.191,455370.0,Q1,2022-Q1,Brunei,ASEAN,16.681536
1,IDN,2023,3.669387,1371169301563.620117,3.308,281190067.0,Q1,2023-Q1,Indonesia,ASEAN,1371.169302
2,KHM,2023,2.127468,42335646895.798401,0.256,17423880.0,Q1,2023-Q1,Cambodia,ASEAN,42.335647
3,KHM,2024,0.808042,46352647037.240601,0.254,17638801.0,Q1,2024-Q1,Cambodia,ASEAN,46.352647
4,LAO,2022,22.956223,15468785203.753201,1.209,7559007.0,Q1,2022-Q1,Laos,ASEAN,15.468785

In [10]:
cube = session.create_cube(table)
print("Cube berhasil dibuat ✓")
print(cube)

Cube berhasil dibuat ✓
<atoti.cube.Cube object at 0x000001F1022123C0>

In [11]:
m = cube.measures
l = cube.levels

print("=== MEASURES ===")
for name in m:
    print(" -", name)

print("\n=== LEVELS ===")
for name in l:
    print(" -", name)

=== MEASURES ===
 - contributors.COUNT
 - gdp_billion_usd.MEAN
 - gdp_billion_usd.SUM
 - gdp_usd.MEAN
 - gdp_usd.SUM
 - inflation_pct.MEAN
 - inflation_pct.SUM
 - population.MEAN
 - population.SUM
 - unemployment_pct.MEAN
 - unemployment_pct.SUM
 - update.TIMESTAMP
 - year.MEAN
 - year.SUM

=== LEVELS ===
 - ('EconomyASEAN', 'period', 'period')
 - ('EconomyASEAN', 'country_name', 'country_name')
 - ('EconomyASEAN', 'region', 'region')
 - ('EconomyASEAN', 'quarter', 'quarter')
 - ('EconomyASEAN', 'economy', 'economy')

Tambah Custom Measures

In [12]:
m["GDP Avg (USD)"]            = tt.agg.mean(table["gdp_usd"])
m["GDP (Billion USD)"]        = tt.agg.mean(table["gdp_billion_usd"])
m["Inflasi Rata-rata (%)"]    = tt.agg.mean(table["inflation_pct"])
m["Pengangguran Rata-rata (%)"] = tt.agg.mean(table["unemployment_pct"])
m["Populasi Total"]           = tt.agg.sum(table["population"])

print("Custom measures berhasil ✓")

Custom measures berhasil ✓

In [15]:
cube.query(
    m["GDP (Billion USD)"],
    m["Inflasi Rata-rata (%)"],
    m["Pengangguran Rata-rata (%)"],
    levels=[l["country_name"], l["period"]]
)

                     GDP (Billion USD) Inflasi Rata-rata (%)  \
country_name period
Brunei       2022-Q1             16.68                  3.68
             2023-Q1             15.10                   .36
             2024-Q1             15.34                  -.39
Cambodia     2022-Q1             39.99                  5.34
             2023-Q1             42.34                  2.13
             2024-Q1             46.35                   .81
Indonesia    2022-Q1          1,319.10                  4.21
             2023-Q1          1,371.17                  3.67
             2024-Q1          1,396.30                  2.18
Laos         2022-Q1             15.47                 22.96
             2023-Q1             15.84                 31.23
             2024-Q1             16.50                 23.13
Malaysia     2022-Q1            407.83                  3.38
             2023-Q1            399.95                  2.49
             2024-Q1            422.23                  1.83
Myanmar      2022-Q1             62.25                  3.38
             2023-Q1             66.76                  3.38
             2024-Q1             74.07                  3.38
Philippines  2022-Q1            404.35                  5.82
             2023-Q1            437.06                  5.98
             2024-Q1            461.62                  3.21
Singapore    2022-Q1            509.02                  6.13
             2023-Q1            505.44                  4.83
             2024-Q1            547.39                  2.39
Thailand     2022-Q1            495.64                 -1.61
             2023-Q1            515.91                  8.48
             2024-Q1            526.52                  1.37
Vietnam      2022-Q1            413.45                  3.16
             2023-Q1            433.86                  3.25
             2024-Q1            476.39                  3.62

                     Pengangguran Rata-rata (%)
country_name period
Brunei       2022-Q1                       5.19
             2023-Q1                       5.30
             2024-Q1                       5.18
Cambodia     2022-Q1                        .24
             2023-Q1                        .26
             2024-Q1                        .25
Indonesia    2022-Q1                       3.46
             2023-Q1                       3.31
             2024-Q1                       3.30
Laos         2022-Q1                       1.21
             2023-Q1                       1.19
             2024-Q1                       1.17
Malaysia     2022-Q1                       3.93
             2023-Q1                       3.86
             2024-Q1                       3.85
Myanmar      2022-Q1                       3.06
             2023-Q1                       2.98
             2024-Q1                       2.89
Philippines  2022-Q1                       2.60
             2023-Q1                       2.20
             2024-Q1                       2.20
Singapore    2022-Q1                       3.59
             2023-Q1                       3.44
             2024-Q1                       2.74
Thailand     2022-Q1                        .94
             2023-Q1                        .73
             2024-Q1                        .78
Vietnam      2022-Q1                       1.57
             2023-Q1                       1.65
             2024-Q1                       1.60

In [16]:
cube.query(
    m["GDP (Billion USD)"],
    m["Populasi Total"],
    levels=[l["country_name"]],
).sort_values("GDP (Billion USD)", ascending=False)

              GDP (Billion USD)  Populasi Total
country_name
Indonesia           1362.190194     843508527.0
Singapore            520.614667      17591530.0
Thailand             512.689547     215105775.0
Vietnam              441.230381     301020533.0
Philippines          434.342169     344699207.0
Malaysia             410.002317     105379464.0
Myanmar               67.693006     162390676.0
Cambodia              42.894276      52264405.0
Laos                  15.938291      22993819.0
Brunei                 15.70581       1377040.0

In [17]:
cube.query(
    m["Inflasi Rata-rata (%)"],
    m["Pengangguran Rata-rata (%)"],
    levels=[l["region"], l["period"]]
)

               Inflasi Rata-rata (%) Pengangguran Rata-rata (%)
region period
ASEAN  2022-Q1                  5.64                       2.58
       2023-Q1                  6.58                       2.49
       2024-Q1                  4.15                       2.40

In [19]:
print(session.url)

http://localhost:55372

Hasil dan Analisis Hasil

Analisis 1: GDP per negara per periode

In [20]:
hasil_gdp = cube.query(
    m["GDP (Billion USD)"],
    m["Inflasi Rata-rata (%)"],
    m["Pengangguran Rata-rata (%)"],
    levels=[l["country_name"], l["period"]]
).sort_values("GDP (Billion USD)", ascending=False)

print("=== RANKING GDP PER NEGARA PER PERIODE ===")
hasil_gdp

=== RANKING GDP PER NEGARA PER PERIODE ===

                      GDP (Billion USD)  Inflasi Rata-rata (%)  \
country_name period
Indonesia    2024-Q1        1396.300098               2.181513
             2023-Q1        1371.169302               3.669387
             2022-Q1        1319.101183               4.209465
Singapore    2024-Q1         547.386646               2.389511
Thailand     2024-Q1         526.517659               1.365805
             2023-Q1         515.906284               8.478052
Singapore    2022-Q1         509.017841               6.130954
             2023-Q1         505.439514               4.833724
Thailand     2022-Q1         495.644698               -1.61068
Vietnam      2024-Q1          476.38823               3.621093
Philippines  2024-Q1          461.61751               3.212605
             2023-Q1         437.055627               5.978025
Vietnam      2023-Q1         433.857681               3.252893
Malaysia     2024-Q1         422.227005                 1.8341
Vietnam      2022-Q1         413.445231               3.156507
Malaysia     2022-Q1         407.830526               3.378699
Philippines  2022-Q1          404.35337               5.821158
Malaysia     2023-Q1         399.949419               2.488866
Myanmar      2024-Q1           74.06835               3.378699
             2023-Q1          66.757619               3.378699
             2022-Q1           62.25305               3.378699
Cambodia     2024-Q1          46.352647               0.808042
             2023-Q1          42.335647               2.127468
             2022-Q1          39.994533               5.343703
Brunei       2022-Q1          16.681536                3.68225
Laos         2024-Q1          16.502933               23.13057
             2023-Q1          15.843156              31.230134
             2022-Q1          15.468785              22.956223
Brunei       2024-Q1          15.340809              -0.388674
             2023-Q1          15.095085               0.357064

                      Pengangguran Rata-rata (%)
country_name period
Indonesia    2024-Q1                       3.301
             2023-Q1                       3.308
             2022-Q1                       3.462
Singapore    2024-Q1                       2.737
Thailand     2024-Q1                       0.781
             2023-Q1                       0.733
Singapore    2022-Q1                       3.591
             2023-Q1                       3.444
Thailand     2022-Q1                        0.94
Vietnam      2024-Q1                       1.602
Philippines  2024-Q1                       2.202
             2023-Q1                         2.2
Vietnam      2023-Q1                       1.645
Malaysia     2024-Q1                       3.846
Vietnam      2022-Q1                        1.57
Malaysia     2022-Q1                        3.93
Philippines  2022-Q1                       2.598
Malaysia     2023-Q1                       3.858
Myanmar      2024-Q1                       2.887
             2023-Q1                       2.977
             2022-Q1                       3.063
Cambodia     2024-Q1                       0.254
             2023-Q1                       0.256
             2022-Q1                       0.245
Brunei       2022-Q1                       5.191
Laos         2024-Q1                       1.174
             2023-Q1                       1.186
             2022-Q1                       1.209
Brunei       2024-Q1                        5.18
             2023-Q1                       5.296

Analisis 2: Ranking GDP tertinggi

In [21]:
ranking_gdp = cube.query(
    m["GDP (Billion USD)"],
    m["Populasi Total"],
    levels=[l["country_name"]]
).sort_values("GDP (Billion USD)", ascending=False)

print("=== RANKING GDP TERTINGGI ASEAN ===")
ranking_gdp

=== RANKING GDP TERTINGGI ASEAN ===

              GDP (Billion USD)  Populasi Total
country_name
Indonesia           1362.190194     843508527.0
Singapore            520.614667      17591530.0
Thailand             512.689547     215105775.0
Vietnam              441.230381     301020533.0
Philippines          434.342169     344699207.0
Malaysia             410.002317     105379464.0
Myanmar               67.693006     162390676.0
Cambodia              42.894276      52264405.0
Laos                  15.938291      22993819.0
Brunei                 15.70581       1377040.0

Analisis 3: Negara inflasi tertinggi

In [22]:
ranking_inflasi = cube.query(
    m["Inflasi Rata-rata (%)"],
    m["GDP (Billion USD)"],
    levels=[l["country_name"]]
).sort_values("Inflasi Rata-rata (%)", ascending=False)

print("=== RANKING INFLASI TERTINGGI ASEAN ===")
ranking_inflasi

=== RANKING INFLASI TERTINGGI ASEAN ===

              Inflasi Rata-rata (%)  GDP (Billion USD)
country_name
Laos                      25.772309          15.938291
Philippines                5.003929         434.342169
Singapore                  4.451396         520.614667
Myanmar                    3.378699          67.693006
Indonesia                  3.353455        1362.190194
Vietnam                    3.343498         441.230381
Cambodia                   2.759738          42.894276
Thailand                   2.744392         512.689547
Malaysia                   2.567221         410.002317
Brunei                      1.21688           15.70581

Analisis 4: Pengangguran tertinggi

In [23]:
ranking_nganggur = cube.query(
    m["Pengangguran Rata-rata (%)"],
    m["Populasi Total"],
    levels=[l["country_name"]]
).sort_values("Pengangguran Rata-rata (%)", ascending=False)

print("=== RANKING PENGANGGURAN TERTINGGI ASEAN ===")
ranking_nganggur

=== RANKING PENGANGGURAN TERTINGGI ASEAN ===

              Pengangguran Rata-rata (%)  Populasi Total
country_name
Brunei                          5.222333       1377040.0
Malaysia                           3.878     105379464.0
Indonesia                          3.357     843508527.0
Singapore                       3.257333      17591530.0
Myanmar                         2.975667     162390676.0
Philippines                     2.333333     344699207.0
Vietnam                         1.605667     301020533.0
Laos                            1.189667      22993819.0
Thailand                           0.818     215105775.0
Cambodia                        0.251667      52264405.0